### ISSUE TITLE
Update tensorflow to 2.5.3

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/meta-coral#13]
There is a new upstream release of TF 2.5, including a lot of patches and fixed CVEs (also to tflite).
The meta-coral layer currently packages 2.5.2. IMO we should update as soon as possible to 2.5.3.

Upstream changelog: https://github.com/tensorflow/tensorflow/releases/tag/v2.5.3

**Comment by jan-kiszka** [comment]
Looks critical also for meta-iot2050 code-freeze @baochengsu.

**Comment by chombourger** [comment]
just seen the message you sent me yesterday but it looks like you have already started the work. well let me know if you'd like to finish this PR or hand-over the remainder of the work to me

**Comment by fmoessbauer** [comment]
> just seen the message you sent me yesterday but it looks like you have already started the work. well let me know if you'd like to finish this PR or hand-over the remainder of the work to me

I just bumped the version and somehow it worked out of the box. To be honest, that was not was I expected...
The packaging should be fine now, but I would appreciate if you could do the testing.

**Comment by chombourger** [comment]
> > just seen the message you sent me yesterday but it looks like you have already started the work. well let me know if you'd like to finish this PR or hand-over the remainder of the work to me
> 
> I just bumped the version and somehow it worked out of the box. To be honest, that was not was I expected... The packaging should be fine now, but I would appreciate if you could do the testing.

That's also what I ended doing in the build I started today. Wanted to get a feel for the issues we would run into but indeed none found so far

**Comment by BaochengSu** [comment]
> Looks critical also for meta-iot2050 code-freeze @BaochengSu.

Definitely we need this before code freezing.
