### ISSUE TITLE
Build failed on ISAR v0.9 (without sbuid)

### ISSUE THREAD

**Issue by AsuraZeng** [siemens/meta-coral#29]
hi 
using the lastet commit:`f1b1d5d9d471c3a2ba2d18bb1631f934839726d3`

error log:
```
ERROR: Error for /work/meta-coral/recipes-python/pycoral/pycoral_2.0.0.bb:do_fetch_bazel_deps[depends], dependency ${SCHROOT_DEP} in ' ${SCHROOT_DEP} bazel-bootstrap:do_deploy_deb' does not contain exactly one ':' character.
 Task 'depends' should be specified in the form 'packagename:task'
ERROR: Command execution failed: Exited with 1

```

**Comment by fmoessbauer** [comment]
That's strange. The commit f1b1d5d9d471c3a2ba2d18bb1631f934839726d3 did not change anything related to the dependencies. It just fixed a build issue due to upstream (packaging) changes.

Could you please try the following in a kas-shell and then retry the build:

`bitbake -c cleanall pycoral bazel-bootstrap`.

**Comment by AsuraZeng** [comment]
seems it is related to the isar version, we use the older one.
for this line has one variable:
https://github.com/siemens/meta-coral/commit/e60d5b91e56ca798d7528d3d9329e55c0ea417f1#diff-cc23e10c983c8fdbfe7ccffc2235f533dbcb2197b837a8e4d14cb75faacd27b8R46

I have checked that our isar version has no variable `SCHROOT_DEP`

**Comment by fmoessbauer** [comment]
Do you use a pre-sbuild version of ISAR?

**Comment by fmoessbauer** [comment]
Unfortunately we can no longer maintain compatibility with both ISAR next and ISAR v0.9.
But as still some downstream layers use ISAR v0.9 and this is also the most recent ISAR release, I added a branch `isar-v0.9`.

Bugfixes and fixes of upstream changes will be backported to this branch.

@AsuraZeng Could you please test if that works for you and report back (and close the issue)?

**Comment by fmoessbauer** [comment]
I checked the meta-iot2050 layer and there it is active and works correctly. Closing.
