### ISSUE TITLE
Adjust to gbp changes in latest Isar

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/meta-coral#36]
https://github.com/ilbers/isar/commit/8530a94bdc8919fadccad13e6061832d2f2c1fcc#diff-b294a6f7f9dd570d7d4d4a6fd015c8d5f6769af8d528dbefcf42faf4d1a6e1cc is changing the `GBP_EXTRA_OPTIONS` semantics. Not sure yet if this is fully compatible with the usage in `recipes-devtools/bazel-bootstrap/bazel-bootstrap_4.1.0+ds-1.bb`. If not, feedback to upstream Isar should be provided ASAP.

**Comment by fmoessbauer** [comment]
Fixed in commit a500879203a4c7f16652e8efe905042260074fd0 as part of #34 .

**Comment by jan-kiszka** [comment]
Upstream is stepping away from this breakage. So this issue should be obsoleted by choosing the right Isar version.

**Comment by fmoessbauer** [comment]
OK, then let's also remove dda16c587e30c8d3955b82b2bf597672b1af2b38 from #34 again.
